### ISSUE TITLE
Publish NPM package

### ISSUE THREAD

**Issue by binarybaron** [libp2p/js-libp2p-rendezvous#10]
Is this project relatively stable? If that's the case, is there a reason you haven't published a NPM package?

Edit: I have found the [package](https://www.npmjs.com/package/libp2p-rendezvous?activeTab=readme). But there hasn't been an update in over 3 years.

**Comment by vasco-santos** [comment]
Thanks for reaching out and apologies for the state of this implementation not being clear in the README. I updated the README to clarify this.

This module has a candidate implementation in a PR, but it still needs to be tested and finished. This will be picked up again once it is a priority per https://github.com/protocol/web3-dev-team/pull/67
